/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteNGModern_100Thin = require('./100Thin/PlaywriteNGModern_100Thin.ttf');
export const PlaywriteNGModern_200ExtraLight = require('./200ExtraLight/PlaywriteNGModern_200ExtraLight.ttf');
export const PlaywriteNGModern_300Light = require('./300Light/PlaywriteNGModern_300Light.ttf');
export const PlaywriteNGModern_400Regular = require('./400Regular/PlaywriteNGModern_400Regular.ttf');
