/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteHR_100Thin = require('./100Thin/PlaywriteHR_100Thin.ttf');
export const PlaywriteHR_200ExtraLight = require('./200ExtraLight/PlaywriteHR_200ExtraLight.ttf');
export const PlaywriteHR_300Light = require('./300Light/PlaywriteHR_300Light.ttf');
export const PlaywriteHR_400Regular = require('./400Regular/PlaywriteHR_400Regular.ttf');
