/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersInlineDisplay_400Regular = require('./BigShouldersInlineDisplay_400Regular.ttf');
