/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const KaiseiHarunoUmi_400Regular = require('./400Regular/KaiseiHarunoUmi_400Regular.ttf');
export const KaiseiHarunoUmi_500Medium = require('./500Medium/KaiseiHarunoUmi_500Medium.ttf');
export const KaiseiHarunoUmi_700Bold = require('./700Bold/KaiseiHarunoUmi_700Bold.ttf');
