/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Puritan_400Regular = require('./400Regular/Puritan_400Regular.ttf');
export const Puritan_400Regular_Italic = require('./400Regular_Italic/Puritan_400Regular_Italic.ttf');
export const Puritan_700Bold = require('./700Bold/Puritan_700Bold.ttf');
export const Puritan_700Bold_Italic = require('./700Bold_Italic/Puritan_700Bold_Italic.ttf');
