/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BigShouldersStencilDisplay_100Thin = require('./100Thin/BigShouldersStencilDisplay_100Thin.ttf');
export const BigShouldersStencilDisplay_200ExtraLight = require('./200ExtraLight/BigShouldersStencilDisplay_200ExtraLight.ttf');
export const BigShouldersStencilDisplay_300Light = require('./300Light/BigShouldersStencilDisplay_300Light.ttf');
export const BigShouldersStencilDisplay_400Regular = require('./400Regular/BigShouldersStencilDisplay_400Regular.ttf');
export const BigShouldersStencilDisplay_500Medium = require('./500Medium/BigShouldersStencilDisplay_500Medium.ttf');
export const BigShouldersStencilDisplay_600SemiBold = require('./600SemiBold/BigShouldersStencilDisplay_600SemiBold.ttf');
export const BigShouldersStencilDisplay_700Bold = require('./700Bold/BigShouldersStencilDisplay_700Bold.ttf');
export const BigShouldersStencilDisplay_800ExtraBold = require('./800ExtraBold/BigShouldersStencilDisplay_800ExtraBold.ttf');
export const BigShouldersStencilDisplay_900Black = require('./900Black/BigShouldersStencilDisplay_900Black.ttf');
