/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Corben_400Regular = require('./400Regular/Corben_400Regular.ttf');
export const Corben_700Bold = require('./700Bold/Corben_700Bold.ttf');
