/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Content_400Regular = require('./400Regular/Content_400Regular.ttf');
export const Content_700Bold = require('./700Bold/Content_700Bold.ttf');
