/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Rowdies_300Light = require('./300Light/Rowdies_300Light.ttf');
export const Rowdies_400Regular = require('./400Regular/Rowdies_400Regular.ttf');
export const Rowdies_700Bold = require('./700Bold/Rowdies_700Bold.ttf');
