/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Oxygen_300Light = require('./300Light/Oxygen_300Light.ttf');
export const Oxygen_400Regular = require('./400Regular/Oxygen_400Regular.ttf');
export const Oxygen_700Bold = require('./700Bold/Oxygen_700Bold.ttf');
