/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const RedactedScript_300Light = require('./300Light/RedactedScript_300Light.ttf');
export const RedactedScript_400Regular = require('./400Regular/RedactedScript_400Regular.ttf');
export const RedactedScript_700Bold = require('./700Bold/RedactedScript_700Bold.ttf');
