/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansTangsa_400Regular = require('./400Regular/NotoSansTangsa_400Regular.ttf');
export const NotoSansTangsa_500Medium = require('./500Medium/NotoSansTangsa_500Medium.ttf');
export const NotoSansTangsa_600SemiBold = require('./600SemiBold/NotoSansTangsa_600SemiBold.ttf');
export const NotoSansTangsa_700Bold = require('./700Bold/NotoSansTangsa_700Bold.ttf');
