/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Manjari_100Thin = require('./100Thin/Manjari_100Thin.ttf');
export const Manjari_400Regular = require('./400Regular/Manjari_400Regular.ttf');
export const Manjari_700Bold = require('./700Bold/Manjari_700Bold.ttf');
