/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Magra_400Regular = require('./400Regular/Magra_400Regular.ttf');
export const Magra_700Bold = require('./700Bold/Magra_700Bold.ttf');
