/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BirthstoneBounce_400Regular = require('./400Regular/BirthstoneBounce_400Regular.ttf');
export const BirthstoneBounce_500Medium = require('./500Medium/BirthstoneBounce_500Medium.ttf');
