/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Phetsarath_400Regular = require('./400Regular/Phetsarath_400Regular.ttf');
export const Phetsarath_700Bold = require('./700Bold/Phetsarath_700Bold.ttf');
