/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoNastaliqUrdu_400Regular = require('./400Regular/NotoNastaliqUrdu_400Regular.ttf');
export const NotoNastaliqUrdu_500Medium = require('./500Medium/NotoNastaliqUrdu_500Medium.ttf');
export const NotoNastaliqUrdu_600SemiBold = require('./600SemiBold/NotoNastaliqUrdu_600SemiBold.ttf');
export const NotoNastaliqUrdu_700Bold = require('./700Bold/NotoNastaliqUrdu_700Bold.ttf');
