/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const ElsieSwashCaps_400Regular = require('./400Regular/ElsieSwashCaps_400Regular.ttf');
export const ElsieSwashCaps_900Black = require('./900Black/ElsieSwashCaps_900Black.ttf');
