/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const CinzelDecorative_400Regular = require('./400Regular/CinzelDecorative_400Regular.ttf');
export const CinzelDecorative_700Bold = require('./700Bold/CinzelDecorative_700Bold.ttf');
export const CinzelDecorative_900Black = require('./900Black/CinzelDecorative_900Black.ttf');
