/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const StardosStencil_400Regular = require('./400Regular/StardosStencil_400Regular.ttf');
export const StardosStencil_700Bold = require('./700Bold/StardosStencil_700Bold.ttf');
