/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Chathura_100Thin = require('./100Thin/Chathura_100Thin.ttf');
export const Chathura_300Light = require('./300Light/Chathura_300Light.ttf');
export const Chathura_400Regular = require('./400Regular/Chathura_400Regular.ttf');
export const Chathura_700Bold = require('./700Bold/Chathura_700Bold.ttf');
export const Chathura_800ExtraBold = require('./800ExtraBold/Chathura_800ExtraBold.ttf');
