/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const ZenKakuGothicAntique_300Light = require('./300Light/ZenKakuGothicAntique_300Light.ttf');
export const ZenKakuGothicAntique_400Regular = require('./400Regular/ZenKakuGothicAntique_400Regular.ttf');
export const ZenKakuGothicAntique_500Medium = require('./500Medium/ZenKakuGothicAntique_500Medium.ttf');
export const ZenKakuGothicAntique_700Bold = require('./700Bold/ZenKakuGothicAntique_700Bold.ttf');
export const ZenKakuGothicAntique_900Black = require('./900Black/ZenKakuGothicAntique_900Black.ttf');
