/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Goldman_400Regular = require('./400Regular/Goldman_400Regular.ttf');
export const Goldman_700Bold = require('./700Bold/Goldman_700Bold.ttf');
