/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Stoke_300Light = require('./300Light/Stoke_300Light.ttf');
export const Stoke_400Regular = require('./400Regular/Stoke_400Regular.ttf');
