/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Parkinsans_300Light = require('./300Light/Parkinsans_300Light.ttf');
export const Parkinsans_400Regular = require('./400Regular/Parkinsans_400Regular.ttf');
export const Parkinsans_500Medium = require('./500Medium/Parkinsans_500Medium.ttf');
export const Parkinsans_600SemiBold = require('./600SemiBold/Parkinsans_600SemiBold.ttf');
export const Parkinsans_700Bold = require('./700Bold/Parkinsans_700Bold.ttf');
export const Parkinsans_800ExtraBold = require('./800ExtraBold/Parkinsans_800ExtraBold.ttf');
