/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansKawi_400Regular = require('./400Regular/NotoSansKawi_400Regular.ttf');
export const NotoSansKawi_500Medium = require('./500Medium/NotoSansKawi_500Medium.ttf');
export const NotoSansKawi_600SemiBold = require('./600SemiBold/NotoSansKawi_600SemiBold.ttf');
export const NotoSansKawi_700Bold = require('./700Bold/NotoSansKawi_700Bold.ttf');
