/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export const __metadata__: Any;
export const LXGWWenKaiMonoTC_300Light: number;
export const LXGWWenKaiMonoTC_400Regular: number;
export const LXGWWenKaiMonoTC_700Bold: number;
