/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const LXGWWenKaiMonoTC_300Light = require('./300Light/LXGWWenKaiMonoTC_300Light.ttf');
export const LXGWWenKaiMonoTC_400Regular = require('./400Regular/LXGWWenKaiMonoTC_400Regular.ttf');
export const LXGWWenKaiMonoTC_700Bold = require('./700Bold/LXGWWenKaiMonoTC_700Bold.ttf');
