/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersStencilText_700Bold = require('./BigShouldersStencilText_700Bold.ttf');
