/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const B612_400Regular = require('./400Regular/B612_400Regular.ttf');
export const B612_400Regular_Italic = require('./400Regular_Italic/B612_400Regular_Italic.ttf');
export const B612_700Bold = require('./700Bold/B612_700Bold.ttf');
export const B612_700Bold_Italic = require('./700Bold_Italic/B612_700Bold_Italic.ttf');
