/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const ArefRuqaa_400Regular = require('./400Regular/ArefRuqaa_400Regular.ttf');
export const ArefRuqaa_700Bold = require('./700Bold/ArefRuqaa_700Bold.ttf');
