/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansAdlamUnjoined_400Regular = require('./400Regular/NotoSansAdlamUnjoined_400Regular.ttf');
export const NotoSansAdlamUnjoined_500Medium = require('./500Medium/NotoSansAdlamUnjoined_500Medium.ttf');
export const NotoSansAdlamUnjoined_600SemiBold = require('./600SemiBold/NotoSansAdlamUnjoined_600SemiBold.ttf');
export const NotoSansAdlamUnjoined_700Bold = require('./700Bold/NotoSansAdlamUnjoined_700Bold.ttf');
