/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const DeliusUnicase_400Regular = require('./400Regular/DeliusUnicase_400Regular.ttf');
export const DeliusUnicase_700Bold = require('./700Bold/DeliusUnicase_700Bold.ttf');
