/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const ZillaSlabHighlight_400Regular = require('./400Regular/ZillaSlabHighlight_400Regular.ttf');
export const ZillaSlabHighlight_700Bold = require('./700Bold/ZillaSlabHighlight_700Bold.ttf');
