/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export const __metadata__: Any;
export const BowlbyOneSC_400Regular: number;
