/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSerifOriya_400Regular = require('./400Regular/NotoSerifOriya_400Regular.ttf');
export const NotoSerifOriya_500Medium = require('./500Medium/NotoSerifOriya_500Medium.ttf');
export const NotoSerifOriya_600SemiBold = require('./600SemiBold/NotoSerifOriya_600SemiBold.ttf');
export const NotoSerifOriya_700Bold = require('./700Bold/NotoSerifOriya_700Bold.ttf');
