/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Amiko_400Regular = require('./400Regular/Amiko_400Regular.ttf');
export const Amiko_600SemiBold = require('./600SemiBold/Amiko_600SemiBold.ttf');
export const Amiko_700Bold = require('./700Bold/Amiko_700Bold.ttf');
