/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const ReemKufiFun_400Regular = require('./400Regular/ReemKufiFun_400Regular.ttf');
export const ReemKufiFun_500Medium = require('./500Medium/ReemKufiFun_500Medium.ttf');
export const ReemKufiFun_600SemiBold = require('./600SemiBold/ReemKufiFun_600SemiBold.ttf');
export const ReemKufiFun_700Bold = require('./700Bold/ReemKufiFun_700Bold.ttf');
