/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Mirza_400Regular = require('./400Regular/Mirza_400Regular.ttf');
export const Mirza_500Medium = require('./500Medium/Mirza_500Medium.ttf');
export const Mirza_600SemiBold = require('./600SemiBold/Mirza_600SemiBold.ttf');
export const Mirza_700Bold = require('./700Bold/Mirza_700Bold.ttf');
