/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansNagMundari_400Regular = require('./400Regular/NotoSansNagMundari_400Regular.ttf');
export const NotoSansNagMundari_500Medium = require('./500Medium/NotoSansNagMundari_500Medium.ttf');
export const NotoSansNagMundari_600SemiBold = require('./600SemiBold/NotoSansNagMundari_600SemiBold.ttf');
export const NotoSansNagMundari_700Bold = require('./700Bold/NotoSansNagMundari_700Bold.ttf');
