/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Carlito_400Regular = require('./400Regular/Carlito_400Regular.ttf');
export const Carlito_400Regular_Italic = require('./400Regular_Italic/Carlito_400Regular_Italic.ttf');
export const Carlito_700Bold = require('./700Bold/Carlito_700Bold.ttf');
export const Carlito_700Bold_Italic = require('./700Bold_Italic/Carlito_700Bold_Italic.ttf');
