/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Astloch_400Regular = require('./400Regular/Astloch_400Regular.ttf');
export const Astloch_700Bold = require('./700Bold/Astloch_700Bold.ttf');
