/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteDEGrund_100Thin = require('./100Thin/PlaywriteDEGrund_100Thin.ttf');
export const PlaywriteDEGrund_200ExtraLight = require('./200ExtraLight/PlaywriteDEGrund_200ExtraLight.ttf');
export const PlaywriteDEGrund_300Light = require('./300Light/PlaywriteDEGrund_300Light.ttf');
export const PlaywriteDEGrund_400Regular = require('./400Regular/PlaywriteDEGrund_400Regular.ttf');
