/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const OldStandardTT_400Regular = require('./400Regular/OldStandardTT_400Regular.ttf');
export const OldStandardTT_400Regular_Italic = require('./400Regular_Italic/OldStandardTT_400Regular_Italic.ttf');
export const OldStandardTT_700Bold = require('./700Bold/OldStandardTT_700Bold.ttf');
