/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Syne_400Regular = require('./400Regular/Syne_400Regular.ttf');
export const Syne_500Medium = require('./500Medium/Syne_500Medium.ttf');
export const Syne_600SemiBold = require('./600SemiBold/Syne_600SemiBold.ttf');
export const Syne_700Bold = require('./700Bold/Syne_700Bold.ttf');
export const Syne_800ExtraBold = require('./800ExtraBold/Syne_800ExtraBold.ttf');
