/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Fondamento_400Regular = require('./400Regular/Fondamento_400Regular.ttf');
export const Fondamento_400Regular_Italic = require('./400Regular_Italic/Fondamento_400Regular_Italic.ttf');
