/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansOlChiki_400Regular = require('./400Regular/NotoSansOlChiki_400Regular.ttf');
export const NotoSansOlChiki_500Medium = require('./500Medium/NotoSansOlChiki_500Medium.ttf');
export const NotoSansOlChiki_600SemiBold = require('./600SemiBold/NotoSansOlChiki_600SemiBold.ttf');
export const NotoSansOlChiki_700Bold = require('./700Bold/NotoSansOlChiki_700Bold.ttf');
