/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const LifeSavers_400Regular = require('./400Regular/LifeSavers_400Regular.ttf');
export const LifeSavers_700Bold = require('./700Bold/LifeSavers_700Bold.ttf');
export const LifeSavers_800ExtraBold = require('./800ExtraBold/LifeSavers_800ExtraBold.ttf');
