/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PassionOne_400Regular = require('./400Regular/PassionOne_400Regular.ttf');
export const PassionOne_700Bold = require('./700Bold/PassionOne_700Bold.ttf');
export const PassionOne_900Black = require('./900Black/PassionOne_900Black.ttf');
