/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersStencilText_400Regular = require('./BigShouldersStencilText_400Regular.ttf');
