/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NanumGothicCoding_400Regular = require('./400Regular/NanumGothicCoding_400Regular.ttf');
export const NanumGothicCoding_700Bold = require('./700Bold/NanumGothicCoding_700Bold.ttf');
