/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const HindMadurai_300Light = require('./300Light/HindMadurai_300Light.ttf');
export const HindMadurai_400Regular = require('./400Regular/HindMadurai_400Regular.ttf');
export const HindMadurai_500Medium = require('./500Medium/HindMadurai_500Medium.ttf');
export const HindMadurai_600SemiBold = require('./600SemiBold/HindMadurai_600SemiBold.ttf');
export const HindMadurai_700Bold = require('./700Bold/HindMadurai_700Bold.ttf');
