/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BigShouldersInlineDisplay_100Thin = require('./100Thin/BigShouldersInlineDisplay_100Thin.ttf');
export const BigShouldersInlineDisplay_200ExtraLight = require('./200ExtraLight/BigShouldersInlineDisplay_200ExtraLight.ttf');
export const BigShouldersInlineDisplay_300Light = require('./300Light/BigShouldersInlineDisplay_300Light.ttf');
export const BigShouldersInlineDisplay_400Regular = require('./400Regular/BigShouldersInlineDisplay_400Regular.ttf');
export const BigShouldersInlineDisplay_500Medium = require('./500Medium/BigShouldersInlineDisplay_500Medium.ttf');
export const BigShouldersInlineDisplay_600SemiBold = require('./600SemiBold/BigShouldersInlineDisplay_600SemiBold.ttf');
export const BigShouldersInlineDisplay_700Bold = require('./700Bold/BigShouldersInlineDisplay_700Bold.ttf');
export const BigShouldersInlineDisplay_800ExtraBold = require('./800ExtraBold/BigShouldersInlineDisplay_800ExtraBold.ttf');
export const BigShouldersInlineDisplay_900Black = require('./900Black/BigShouldersInlineDisplay_900Black.ttf');
