/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Flamenco_300Light = require('./300Light/Flamenco_300Light.ttf');
export const Flamenco_400Regular = require('./400Regular/Flamenco_400Regular.ttf');
