/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const MountainsofChristmas_400Regular = require('./400Regular/MountainsofChristmas_400Regular.ttf');
export const MountainsofChristmas_700Bold = require('./700Bold/MountainsofChristmas_700Bold.ttf');
