/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersInlineText_200ExtraLight = require('./BigShouldersInlineText_200ExtraLight.ttf');
