/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export const __metadata__: Any;
export const WindSong_400Regular: number;
export const WindSong_500Medium: number;
