/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const WindSong_400Regular = require('./400Regular/WindSong_400Regular.ttf');
export const WindSong_500Medium = require('./500Medium/WindSong_500Medium.ttf');
