/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Arsenal_400Regular = require('./400Regular/Arsenal_400Regular.ttf');
export const Arsenal_400Regular_Italic = require('./400Regular_Italic/Arsenal_400Regular_Italic.ttf');
export const Arsenal_700Bold = require('./700Bold/Arsenal_700Bold.ttf');
export const Arsenal_700Bold_Italic = require('./700Bold_Italic/Arsenal_700Bold_Italic.ttf');
