/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Silkscreen_400Regular = require('./400Regular/Silkscreen_400Regular.ttf');
export const Silkscreen_700Bold = require('./700Bold/Silkscreen_700Bold.ttf');
