/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const CormorantUnicase_300Light = require('./300Light/CormorantUnicase_300Light.ttf');
export const CormorantUnicase_400Regular = require('./400Regular/CormorantUnicase_400Regular.ttf');
export const CormorantUnicase_500Medium = require('./500Medium/CormorantUnicase_500Medium.ttf');
export const CormorantUnicase_600SemiBold = require('./600SemiBold/CormorantUnicase_600SemiBold.ttf');
export const CormorantUnicase_700Bold = require('./700Bold/CormorantUnicase_700Bold.ttf');
