/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const CabinCondensed_400Regular = require('./400Regular/CabinCondensed_400Regular.ttf');
export const CabinCondensed_500Medium = require('./500Medium/CabinCondensed_500Medium.ttf');
export const CabinCondensed_600SemiBold = require('./600SemiBold/CabinCondensed_600SemiBold.ttf');
export const CabinCondensed_700Bold = require('./700Bold/CabinCondensed_700Bold.ttf');
