/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BIZUDMincho_400Regular = require('./400Regular/BIZUDMincho_400Regular.ttf');
export const BIZUDMincho_700Bold = require('./700Bold/BIZUDMincho_700Bold.ttf');
