/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Skranji_400Regular = require('./400Regular/Skranji_400Regular.ttf');
export const Skranji_700Bold = require('./700Bold/Skranji_700Bold.ttf');
