/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansCanadianAboriginal_100Thin = require('./100Thin/NotoSansCanadianAboriginal_100Thin.ttf');
export const NotoSansCanadianAboriginal_200ExtraLight = require('./200ExtraLight/NotoSansCanadianAboriginal_200ExtraLight.ttf');
export const NotoSansCanadianAboriginal_300Light = require('./300Light/NotoSansCanadianAboriginal_300Light.ttf');
export const NotoSansCanadianAboriginal_400Regular = require('./400Regular/NotoSansCanadianAboriginal_400Regular.ttf');
export const NotoSansCanadianAboriginal_500Medium = require('./500Medium/NotoSansCanadianAboriginal_500Medium.ttf');
export const NotoSansCanadianAboriginal_600SemiBold = require('./600SemiBold/NotoSansCanadianAboriginal_600SemiBold.ttf');
export const NotoSansCanadianAboriginal_700Bold = require('./700Bold/NotoSansCanadianAboriginal_700Bold.ttf');
export const NotoSansCanadianAboriginal_800ExtraBold = require('./800ExtraBold/NotoSansCanadianAboriginal_800ExtraBold.ttf');
export const NotoSansCanadianAboriginal_900Black = require('./900Black/NotoSansCanadianAboriginal_900Black.ttf');
