/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Almarai_300Light = require('./300Light/Almarai_300Light.ttf');
export const Almarai_400Regular = require('./400Regular/Almarai_400Regular.ttf');
export const Almarai_700Bold = require('./700Bold/Almarai_700Bold.ttf');
export const Almarai_800ExtraBold = require('./800ExtraBold/Almarai_800ExtraBold.ttf');
