/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Coda_400Regular = require('./400Regular/Coda_400Regular.ttf');
export const Coda_800ExtraBold = require('./800ExtraBold/Coda_800ExtraBold.ttf');
