/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansHanifiRohingya_400Regular = require('./400Regular/NotoSansHanifiRohingya_400Regular.ttf');
export const NotoSansHanifiRohingya_500Medium = require('./500Medium/NotoSansHanifiRohingya_500Medium.ttf');
export const NotoSansHanifiRohingya_600SemiBold = require('./600SemiBold/NotoSansHanifiRohingya_600SemiBold.ttf');
export const NotoSansHanifiRohingya_700Bold = require('./700Bold/NotoSansHanifiRohingya_700Bold.ttf');
