/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Gwendolyn_400Regular = require('./400Regular/Gwendolyn_400Regular.ttf');
export const Gwendolyn_700Bold = require('./700Bold/Gwendolyn_700Bold.ttf');
