/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteBEVLG_100Thin = require('./100Thin/PlaywriteBEVLG_100Thin.ttf');
export const PlaywriteBEVLG_200ExtraLight = require('./200ExtraLight/PlaywriteBEVLG_200ExtraLight.ttf');
export const PlaywriteBEVLG_300Light = require('./300Light/PlaywriteBEVLG_300Light.ttf');
export const PlaywriteBEVLG_400Regular = require('./400Regular/PlaywriteBEVLG_400Regular.ttf');
