/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Gayathri_100Thin = require('./100Thin/Gayathri_100Thin.ttf');
export const Gayathri_400Regular = require('./400Regular/Gayathri_400Regular.ttf');
export const Gayathri_700Bold = require('./700Bold/Gayathri_700Bold.ttf');
