/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Brawler_400Regular = require('./400Regular/Brawler_400Regular.ttf');
export const Brawler_700Bold = require('./700Bold/Brawler_700Bold.ttf');
