/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Teko_300Light = require('./300Light/Teko_300Light.ttf');
export const Teko_400Regular = require('./400Regular/Teko_400Regular.ttf');
export const Teko_500Medium = require('./500Medium/Teko_500Medium.ttf');
export const Teko_600SemiBold = require('./600SemiBold/Teko_600SemiBold.ttf');
export const Teko_700Bold = require('./700Bold/Teko_700Bold.ttf');
