/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Domine_400Regular = require('./400Regular/Domine_400Regular.ttf');
export const Domine_500Medium = require('./500Medium/Domine_500Medium.ttf');
export const Domine_600SemiBold = require('./600SemiBold/Domine_600SemiBold.ttf');
export const Domine_700Bold = require('./700Bold/Domine_700Bold.ttf');
