/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteES_100Thin = require('./100Thin/PlaywriteES_100Thin.ttf');
export const PlaywriteES_200ExtraLight = require('./200ExtraLight/PlaywriteES_200ExtraLight.ttf');
export const PlaywriteES_300Light = require('./300Light/PlaywriteES_300Light.ttf');
export const PlaywriteES_400Regular = require('./400Regular/PlaywriteES_400Regular.ttf');
