/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Syncopate_400Regular = require('./400Regular/Syncopate_400Regular.ttf');
export const Syncopate_700Bold = require('./700Bold/Syncopate_700Bold.ttf');
