/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Khand_300Light = require('./300Light/Khand_300Light.ttf');
export const Khand_400Regular = require('./400Regular/Khand_400Regular.ttf');
export const Khand_500Medium = require('./500Medium/Khand_500Medium.ttf');
export const Khand_600SemiBold = require('./600SemiBold/Khand_600SemiBold.ttf');
export const Khand_700Bold = require('./700Bold/Khand_700Bold.ttf');
