/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Halant_300Light = require('./300Light/Halant_300Light.ttf');
export const Halant_400Regular = require('./400Regular/Halant_400Regular.ttf');
export const Halant_500Medium = require('./500Medium/Halant_500Medium.ttf');
export const Halant_600SemiBold = require('./600SemiBold/Halant_600SemiBold.ttf');
export const Halant_700Bold = require('./700Bold/Halant_700Bold.ttf');
