/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Play_400Regular = require('./400Regular/Play_400Regular.ttf');
export const Play_700Bold = require('./700Bold/Play_700Bold.ttf');
