/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersInlineDisplay_800ExtraBold = require('./BigShouldersInlineDisplay_800ExtraBold.ttf');
