/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Cambay_400Regular = require('./400Regular/Cambay_400Regular.ttf');
export const Cambay_400Regular_Italic = require('./400Regular_Italic/Cambay_400Regular_Italic.ttf');
export const Cambay_700Bold = require('./700Bold/Cambay_700Bold.ttf');
export const Cambay_700Bold_Italic = require('./700Bold_Italic/Cambay_700Bold_Italic.ttf');
