/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Recursive_300Light = require('./300Light/Recursive_300Light.ttf');
export const Recursive_400Regular = require('./400Regular/Recursive_400Regular.ttf');
export const Recursive_500Medium = require('./500Medium/Recursive_500Medium.ttf');
export const Recursive_600SemiBold = require('./600SemiBold/Recursive_600SemiBold.ttf');
export const Recursive_700Bold = require('./700Bold/Recursive_700Bold.ttf');
export const Recursive_800ExtraBold = require('./800ExtraBold/Recursive_800ExtraBold.ttf');
export const Recursive_900Black = require('./900Black/Recursive_900Black.ttf');
