/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NewsCycle_400Regular = require('./400Regular/NewsCycle_400Regular.ttf');
export const NewsCycle_700Bold = require('./700Bold/NewsCycle_700Bold.ttf');
