/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const KiwiMaru_300Light = require('./300Light/KiwiMaru_300Light.ttf');
export const KiwiMaru_400Regular = require('./400Regular/KiwiMaru_400Regular.ttf');
export const KiwiMaru_500Medium = require('./500Medium/KiwiMaru_500Medium.ttf');
