/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Gorditas_400Regular = require('./400Regular/Gorditas_400Regular.ttf');
export const Gorditas_700Bold = require('./700Bold/Gorditas_700Bold.ttf');
