/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteDESAS_100Thin = require('./100Thin/PlaywriteDESAS_100Thin.ttf');
export const PlaywriteDESAS_200ExtraLight = require('./200ExtraLight/PlaywriteDESAS_200ExtraLight.ttf');
export const PlaywriteDESAS_300Light = require('./300Light/PlaywriteDESAS_300Light.ttf');
export const PlaywriteDESAS_400Regular = require('./400Regular/PlaywriteDESAS_400Regular.ttf');
