/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteAUTAS_100Thin = require('./100Thin/PlaywriteAUTAS_100Thin.ttf');
export const PlaywriteAUTAS_200ExtraLight = require('./200ExtraLight/PlaywriteAUTAS_200ExtraLight.ttf');
export const PlaywriteAUTAS_300Light = require('./300Light/PlaywriteAUTAS_300Light.ttf');
export const PlaywriteAUTAS_400Regular = require('./400Regular/PlaywriteAUTAS_400Regular.ttf');
