/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Kalam_300Light = require('./300Light/Kalam_300Light.ttf');
export const Kalam_400Regular = require('./400Regular/Kalam_400Regular.ttf');
export const Kalam_700Bold = require('./700Bold/Kalam_700Bold.ttf');
