/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansSundanese_400Regular = require('./400Regular/NotoSansSundanese_400Regular.ttf');
export const NotoSansSundanese_500Medium = require('./500Medium/NotoSansSundanese_500Medium.ttf');
export const NotoSansSundanese_600SemiBold = require('./600SemiBold/NotoSansSundanese_600SemiBold.ttf');
export const NotoSansSundanese_700Bold = require('./700Bold/NotoSansSundanese_700Bold.ttf');
