/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywritePT_100Thin = require('./100Thin/PlaywritePT_100Thin.ttf');
export const PlaywritePT_200ExtraLight = require('./200ExtraLight/PlaywritePT_200ExtraLight.ttf');
export const PlaywritePT_300Light = require('./300Light/PlaywritePT_300Light.ttf');
export const PlaywritePT_400Regular = require('./400Regular/PlaywritePT_400Regular.ttf');
