/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansVithkuqi_400Regular = require('./400Regular/NotoSansVithkuqi_400Regular.ttf');
export const NotoSansVithkuqi_500Medium = require('./500Medium/NotoSansVithkuqi_500Medium.ttf');
export const NotoSansVithkuqi_600SemiBold = require('./600SemiBold/NotoSansVithkuqi_600SemiBold.ttf');
export const NotoSansVithkuqi_700Bold = require('./700Bold/NotoSansVithkuqi_700Bold.ttf');
