/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteFRTrad_100Thin = require('./100Thin/PlaywriteFRTrad_100Thin.ttf');
export const PlaywriteFRTrad_200ExtraLight = require('./200ExtraLight/PlaywriteFRTrad_200ExtraLight.ttf');
export const PlaywriteFRTrad_300Light = require('./300Light/PlaywriteFRTrad_300Light.ttf');
export const PlaywriteFRTrad_400Regular = require('./400Regular/PlaywriteFRTrad_400Regular.ttf');
