/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansJavanese_400Regular = require('./400Regular/NotoSansJavanese_400Regular.ttf');
export const NotoSansJavanese_500Medium = require('./500Medium/NotoSansJavanese_500Medium.ttf');
export const NotoSansJavanese_600SemiBold = require('./600SemiBold/NotoSansJavanese_600SemiBold.ttf');
export const NotoSansJavanese_700Bold = require('./700Bold/NotoSansJavanese_700Bold.ttf');
