/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const IstokWeb_400Regular = require('./400Regular/IstokWeb_400Regular.ttf');
export const IstokWeb_400Regular_Italic = require('./400Regular_Italic/IstokWeb_400Regular_Italic.ttf');
export const IstokWeb_700Bold = require('./700Bold/IstokWeb_700Bold.ttf');
export const IstokWeb_700Bold_Italic = require('./700Bold_Italic/IstokWeb_700Bold_Italic.ttf');
