/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersText_200ExtraLight = require('./BigShouldersText_200ExtraLight.ttf');
