/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteUSModern_100Thin = require('./100Thin/PlaywriteUSModern_100Thin.ttf');
export const PlaywriteUSModern_200ExtraLight = require('./200ExtraLight/PlaywriteUSModern_200ExtraLight.ttf');
export const PlaywriteUSModern_300Light = require('./300Light/PlaywriteUSModern_300Light.ttf');
export const PlaywriteUSModern_400Regular = require('./400Regular/PlaywriteUSModern_400Regular.ttf');
