/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const MontserratSubrayada_400Regular = require('./400Regular/MontserratSubrayada_400Regular.ttf');
export const MontserratSubrayada_700Bold = require('./700Bold/MontserratSubrayada_700Bold.ttf');
