/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Rufina_400Regular = require('./400Regular/Rufina_400Regular.ttf');
export const Rufina_700Bold = require('./700Bold/Rufina_700Bold.ttf');
