/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const EduNSWACTFoundation_400Regular = require('./400Regular/EduNSWACTFoundation_400Regular.ttf');
export const EduNSWACTFoundation_500Medium = require('./500Medium/EduNSWACTFoundation_500Medium.ttf');
export const EduNSWACTFoundation_600SemiBold = require('./600SemiBold/EduNSWACTFoundation_600SemiBold.ttf');
export const EduNSWACTFoundation_700Bold = require('./700Bold/EduNSWACTFoundation_700Bold.ttf');
