/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BigShouldersInlineText_100Thin = require('./100Thin/BigShouldersInlineText_100Thin.ttf');
export const BigShouldersInlineText_200ExtraLight = require('./200ExtraLight/BigShouldersInlineText_200ExtraLight.ttf');
export const BigShouldersInlineText_300Light = require('./300Light/BigShouldersInlineText_300Light.ttf');
export const BigShouldersInlineText_400Regular = require('./400Regular/BigShouldersInlineText_400Regular.ttf');
export const BigShouldersInlineText_500Medium = require('./500Medium/BigShouldersInlineText_500Medium.ttf');
export const BigShouldersInlineText_600SemiBold = require('./600SemiBold/BigShouldersInlineText_600SemiBold.ttf');
export const BigShouldersInlineText_700Bold = require('./700Bold/BigShouldersInlineText_700Bold.ttf');
export const BigShouldersInlineText_800ExtraBold = require('./800ExtraBold/BigShouldersInlineText_800ExtraBold.ttf');
export const BigShouldersInlineText_900Black = require('./900Black/BigShouldersInlineText_900Black.ttf');
