/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Baskervville_400Regular = require('./400Regular/Baskervville_400Regular.ttf');
export const Baskervville_400Regular_Italic = require('./400Regular_Italic/Baskervville_400Regular_Italic.ttf');
