/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteCO_100Thin = require('./100Thin/PlaywriteCO_100Thin.ttf');
export const PlaywriteCO_200ExtraLight = require('./200ExtraLight/PlaywriteCO_200ExtraLight.ttf');
export const PlaywriteCO_300Light = require('./300Light/PlaywriteCO_300Light.ttf');
export const PlaywriteCO_400Regular = require('./400Regular/PlaywriteCO_400Regular.ttf');
