/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Amita_400Regular = require('./400Regular/Amita_400Regular.ttf');
export const Amita_700Bold = require('./700Bold/Amita_700Bold.ttf');
