/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const TsukimiRounded_300Light = require('./300Light/TsukimiRounded_300Light.ttf');
export const TsukimiRounded_400Regular = require('./400Regular/TsukimiRounded_400Regular.ttf');
export const TsukimiRounded_500Medium = require('./500Medium/TsukimiRounded_500Medium.ttf');
export const TsukimiRounded_600SemiBold = require('./600SemiBold/TsukimiRounded_600SemiBold.ttf');
export const TsukimiRounded_700Bold = require('./700Bold/TsukimiRounded_700Bold.ttf');
