/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Volkhov_400Regular = require('./400Regular/Volkhov_400Regular.ttf');
export const Volkhov_400Regular_Italic = require('./400Regular_Italic/Volkhov_400Regular_Italic.ttf');
export const Volkhov_700Bold = require('./700Bold/Volkhov_700Bold.ttf');
export const Volkhov_700Bold_Italic = require('./700Bold_Italic/Volkhov_700Bold_Italic.ttf');
