/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BalooTamma2_400Regular = require('./400Regular/BalooTamma2_400Regular.ttf');
export const BalooTamma2_500Medium = require('./500Medium/BalooTamma2_500Medium.ttf');
export const BalooTamma2_600SemiBold = require('./600SemiBold/BalooTamma2_600SemiBold.ttf');
export const BalooTamma2_700Bold = require('./700Bold/BalooTamma2_700Bold.ttf');
export const BalooTamma2_800ExtraBold = require('./800ExtraBold/BalooTamma2_800ExtraBold.ttf');
