/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const LibreCaslonText_400Regular = require('./400Regular/LibreCaslonText_400Regular.ttf');
export const LibreCaslonText_400Regular_Italic = require('./400Regular_Italic/LibreCaslonText_400Regular_Italic.ttf');
export const LibreCaslonText_700Bold = require('./700Bold/LibreCaslonText_700Bold.ttf');
