/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersInlineDisplay_900Black = require('./BigShouldersInlineDisplay_900Black.ttf');
