/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const LXGWWenKaiTC_300Light = require('./300Light/LXGWWenKaiTC_300Light.ttf');
export const LXGWWenKaiTC_400Regular = require('./400Regular/LXGWWenKaiTC_400Regular.ttf');
export const LXGWWenKaiTC_700Bold = require('./700Bold/LXGWWenKaiTC_700Bold.ttf');
