/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const AnnapurnaSIL_400Regular = require('./400Regular/AnnapurnaSIL_400Regular.ttf');
export const AnnapurnaSIL_700Bold = require('./700Bold/AnnapurnaSIL_700Bold.ttf');
