/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Athiti_200ExtraLight = require('./200ExtraLight/Athiti_200ExtraLight.ttf');
export const Athiti_300Light = require('./300Light/Athiti_300Light.ttf');
export const Athiti_400Regular = require('./400Regular/Athiti_400Regular.ttf');
export const Athiti_500Medium = require('./500Medium/Athiti_500Medium.ttf');
export const Athiti_600SemiBold = require('./600SemiBold/Athiti_600SemiBold.ttf');
export const Athiti_700Bold = require('./700Bold/Athiti_700Bold.ttf');
