/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansMedefaidrin_400Regular = require('./400Regular/NotoSansMedefaidrin_400Regular.ttf');
export const NotoSansMedefaidrin_500Medium = require('./500Medium/NotoSansMedefaidrin_500Medium.ttf');
export const NotoSansMedefaidrin_600SemiBold = require('./600SemiBold/NotoSansMedefaidrin_600SemiBold.ttf');
export const NotoSansMedefaidrin_700Bold = require('./700Bold/NotoSansMedefaidrin_700Bold.ttf');
