/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PixelifySans_400Regular = require('./400Regular/PixelifySans_400Regular.ttf');
export const PixelifySans_500Medium = require('./500Medium/PixelifySans_500Medium.ttf');
export const PixelifySans_600SemiBold = require('./600SemiBold/PixelifySans_600SemiBold.ttf');
export const PixelifySans_700Bold = require('./700Bold/PixelifySans_700Bold.ttf');
