/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Podkova_400Regular = require('./400Regular/Podkova_400Regular.ttf');
export const Podkova_500Medium = require('./500Medium/Podkova_500Medium.ttf');
export const Podkova_600SemiBold = require('./600SemiBold/Podkova_600SemiBold.ttf');
export const Podkova_700Bold = require('./700Bold/Podkova_700Bold.ttf');
export const Podkova_800ExtraBold = require('./800ExtraBold/Podkova_800ExtraBold.ttf');
