/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteAUSA_100Thin = require('./100Thin/PlaywriteAUSA_100Thin.ttf');
export const PlaywriteAUSA_200ExtraLight = require('./200ExtraLight/PlaywriteAUSA_200ExtraLight.ttf');
export const PlaywriteAUSA_300Light = require('./300Light/PlaywriteAUSA_300Light.ttf');
export const PlaywriteAUSA_400Regular = require('./400Regular/PlaywriteAUSA_400Regular.ttf');
