/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BalooBhaijaan2_400Regular = require('./400Regular/BalooBhaijaan2_400Regular.ttf');
export const BalooBhaijaan2_500Medium = require('./500Medium/BalooBhaijaan2_500Medium.ttf');
export const BalooBhaijaan2_600SemiBold = require('./600SemiBold/BalooBhaijaan2_600SemiBold.ttf');
export const BalooBhaijaan2_700Bold = require('./700Bold/BalooBhaijaan2_700Bold.ttf');
export const BalooBhaijaan2_800ExtraBold = require('./800ExtraBold/BalooBhaijaan2_800ExtraBold.ttf');
