/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PTSerif_400Regular = require('./400Regular/PTSerif_400Regular.ttf');
export const PTSerif_400Regular_Italic = require('./400Regular_Italic/PTSerif_400Regular_Italic.ttf');
export const PTSerif_700Bold = require('./700Bold/PTSerif_700Bold.ttf');
export const PTSerif_700Bold_Italic = require('./700Bold_Italic/PTSerif_700Bold_Italic.ttf');
