/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Belanosima_400Regular = require('./400Regular/Belanosima_400Regular.ttf');
export const Belanosima_600SemiBold = require('./600SemiBold/Belanosima_600SemiBold.ttf');
export const Belanosima_700Bold = require('./700Bold/Belanosima_700Bold.ttf');
