/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersStencilText_900Black = require('./BigShouldersStencilText_900Black.ttf');
