/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteHU_100Thin = require('./100Thin/PlaywriteHU_100Thin.ttf');
export const PlaywriteHU_200ExtraLight = require('./200ExtraLight/PlaywriteHU_200ExtraLight.ttf');
export const PlaywriteHU_300Light = require('./300Light/PlaywriteHU_300Light.ttf');
export const PlaywriteHU_400Regular = require('./400Regular/PlaywriteHU_400Regular.ttf');
