/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteBEWAL_100Thin = require('./100Thin/PlaywriteBEWAL_100Thin.ttf');
export const PlaywriteBEWAL_200ExtraLight = require('./200ExtraLight/PlaywriteBEWAL_200ExtraLight.ttf');
export const PlaywriteBEWAL_300Light = require('./300Light/PlaywriteBEWAL_300Light.ttf');
export const PlaywriteBEWAL_400Regular = require('./400Regular/PlaywriteBEWAL_400Regular.ttf');
