/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const DynaPuff_400Regular = require('./400Regular/DynaPuff_400Regular.ttf');
export const DynaPuff_500Medium = require('./500Medium/DynaPuff_500Medium.ttf');
export const DynaPuff_600SemiBold = require('./600SemiBold/DynaPuff_600SemiBold.ttf');
export const DynaPuff_700Bold = require('./700Bold/DynaPuff_700Bold.ttf');
