/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteMX_100Thin = require('./100Thin/PlaywriteMX_100Thin.ttf');
export const PlaywriteMX_200ExtraLight = require('./200ExtraLight/PlaywriteMX_200ExtraLight.ttf');
export const PlaywriteMX_300Light = require('./300Light/PlaywriteMX_300Light.ttf');
export const PlaywriteMX_400Regular = require('./400Regular/PlaywriteMX_400Regular.ttf');
