/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const DMSerifDisplay_400Regular = require('./400Regular/DMSerifDisplay_400Regular.ttf');
export const DMSerifDisplay_400Regular_Italic = require('./400Regular_Italic/DMSerifDisplay_400Regular_Italic.ttf');
