/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Moulpali_400Regular = require('./400Regular/Moulpali_400Regular.ttf');
