/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const AmaticSC_400Regular = require('./400Regular/AmaticSC_400Regular.ttf');
export const AmaticSC_700Bold = require('./700Bold/AmaticSC_700Bold.ttf');
