/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteITModerna_100Thin = require('./100Thin/PlaywriteITModerna_100Thin.ttf');
export const PlaywriteITModerna_200ExtraLight = require('./200ExtraLight/PlaywriteITModerna_200ExtraLight.ttf');
export const PlaywriteITModerna_300Light = require('./300Light/PlaywriteITModerna_300Light.ttf');
export const PlaywriteITModerna_400Regular = require('./400Regular/PlaywriteITModerna_400Regular.ttf');
