/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const AtkinsonHyperlegible_400Regular = require('./400Regular/AtkinsonHyperlegible_400Regular.ttf');
export const AtkinsonHyperlegible_400Regular_Italic = require('./400Regular_Italic/AtkinsonHyperlegible_400Regular_Italic.ttf');
export const AtkinsonHyperlegible_700Bold = require('./700Bold/AtkinsonHyperlegible_700Bold.ttf');
export const AtkinsonHyperlegible_700Bold_Italic = require('./700Bold_Italic/AtkinsonHyperlegible_700Bold_Italic.ttf');
