/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersDisplay_200ExtraLight = require('./BigShouldersDisplay_200ExtraLight.ttf');
