/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const TaiHeritagePro_400Regular = require('./400Regular/TaiHeritagePro_400Regular.ttf');
export const TaiHeritagePro_700Bold = require('./700Bold/TaiHeritagePro_700Bold.ttf');
