/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const ZenOldMincho_400Regular = require('./400Regular/ZenOldMincho_400Regular.ttf');
export const ZenOldMincho_500Medium = require('./500Medium/ZenOldMincho_500Medium.ttf');
export const ZenOldMincho_600SemiBold = require('./600SemiBold/ZenOldMincho_600SemiBold.ttf');
export const ZenOldMincho_700Bold = require('./700Bold/ZenOldMincho_700Bold.ttf');
export const ZenOldMincho_900Black = require('./900Black/ZenOldMincho_900Black.ttf');
