/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NoticiaText_400Regular = require('./400Regular/NoticiaText_400Regular.ttf');
export const NoticiaText_400Regular_Italic = require('./400Regular_Italic/NoticiaText_400Regular_Italic.ttf');
export const NoticiaText_700Bold = require('./700Bold/NoticiaText_700Bold.ttf');
export const NoticiaText_700Bold_Italic = require('./700Bold_Italic/NoticiaText_700Bold_Italic.ttf');
