/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const AbhayaLibre_400Regular = require('./400Regular/AbhayaLibre_400Regular.ttf');
export const AbhayaLibre_500Medium = require('./500Medium/AbhayaLibre_500Medium.ttf');
export const AbhayaLibre_600SemiBold = require('./600SemiBold/AbhayaLibre_600SemiBold.ttf');
export const AbhayaLibre_700Bold = require('./700Bold/AbhayaLibre_700Bold.ttf');
export const AbhayaLibre_800ExtraBold = require('./800ExtraBold/AbhayaLibre_800ExtraBold.ttf');
