/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Srisakdi_400Regular = require('./400Regular/Srisakdi_400Regular.ttf');
export const Srisakdi_700Bold = require('./700Bold/Srisakdi_700Bold.ttf');
