/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const OleoScript_400Regular = require('./400Regular/OleoScript_400Regular.ttf');
export const OleoScript_700Bold = require('./700Bold/OleoScript_700Bold.ttf');
