/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const InriaSerif_300Light = require('./300Light/InriaSerif_300Light.ttf');
export const InriaSerif_300Light_Italic = require('./300Light_Italic/InriaSerif_300Light_Italic.ttf');
export const InriaSerif_400Regular = require('./400Regular/InriaSerif_400Regular.ttf');
export const InriaSerif_400Regular_Italic = require('./400Regular_Italic/InriaSerif_400Regular_Italic.ttf');
export const InriaSerif_700Bold = require('./700Bold/InriaSerif_700Bold.ttf');
export const InriaSerif_700Bold_Italic = require('./700Bold_Italic/InriaSerif_700Bold_Italic.ttf');
