/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Sura_400Regular = require('./400Regular/Sura_400Regular.ttf');
export const Sura_700Bold = require('./700Bold/Sura_700Bold.ttf');
