/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const TheNautigal_400Regular = require('./400Regular/TheNautigal_400Regular.ttf');
export const TheNautigal_700Bold = require('./700Bold/TheNautigal_700Bold.ttf');
