/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersInlineDisplay_600SemiBold = require('./BigShouldersInlineDisplay_600SemiBold.ttf');
