/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const MaterialSymbolsOutlined_100Thin = require('./100Thin/MaterialSymbolsOutlined_100Thin.ttf');
export const MaterialSymbolsOutlined_200ExtraLight = require('./200ExtraLight/MaterialSymbolsOutlined_200ExtraLight.ttf');
export const MaterialSymbolsOutlined_300Light = require('./300Light/MaterialSymbolsOutlined_300Light.ttf');
export const MaterialSymbolsOutlined_400Regular = require('./400Regular/MaterialSymbolsOutlined_400Regular.ttf');
export const MaterialSymbolsOutlined_500Medium = require('./500Medium/MaterialSymbolsOutlined_500Medium.ttf');
export const MaterialSymbolsOutlined_600SemiBold = require('./600SemiBold/MaterialSymbolsOutlined_600SemiBold.ttf');
export const MaterialSymbolsOutlined_700Bold = require('./700Bold/MaterialSymbolsOutlined_700Bold.ttf');
