/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const DancingScript_400Regular = require('./400Regular/DancingScript_400Regular.ttf');
export const DancingScript_500Medium = require('./500Medium/DancingScript_500Medium.ttf');
export const DancingScript_600SemiBold = require('./600SemiBold/DancingScript_600SemiBold.ttf');
export const DancingScript_700Bold = require('./700Bold/DancingScript_700Bold.ttf');
