/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const KayPhoDu_400Regular = require('./400Regular/KayPhoDu_400Regular.ttf');
export const KayPhoDu_500Medium = require('./500Medium/KayPhoDu_500Medium.ttf');
export const KayPhoDu_600SemiBold = require('./600SemiBold/KayPhoDu_600SemiBold.ttf');
export const KayPhoDu_700Bold = require('./700Bold/KayPhoDu_700Bold.ttf');
