/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Lunasima_400Regular = require('./400Regular/Lunasima_400Regular.ttf');
export const Lunasima_700Bold = require('./700Bold/Lunasima_700Bold.ttf');
