/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Tangerine_400Regular = require('./400Regular/Tangerine_400Regular.ttf');
export const Tangerine_700Bold = require('./700Bold/Tangerine_700Bold.ttf');
