/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Caudex_400Regular = require('./400Regular/Caudex_400Regular.ttf');
export const Caudex_400Regular_Italic = require('./400Regular_Italic/Caudex_400Regular_Italic.ttf');
export const Caudex_700Bold = require('./700Bold/Caudex_700Bold.ttf');
export const Caudex_700Bold_Italic = require('./700Bold_Italic/Caudex_700Bold_Italic.ttf');
