/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersInlineDisplay_100Thin = require('./BigShouldersInlineDisplay_100Thin.ttf');
