/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Enriqueta_400Regular = require('./400Regular/Enriqueta_400Regular.ttf');
export const Enriqueta_500Medium = require('./500Medium/Enriqueta_500Medium.ttf');
export const Enriqueta_600SemiBold = require('./600SemiBold/Enriqueta_600SemiBold.ttf');
export const Enriqueta_700Bold = require('./700Bold/Enriqueta_700Bold.ttf');
