/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteIN_100Thin = require('./100Thin/PlaywriteIN_100Thin.ttf');
export const PlaywriteIN_200ExtraLight = require('./200ExtraLight/PlaywriteIN_200ExtraLight.ttf');
export const PlaywriteIN_300Light = require('./300Light/PlaywriteIN_300Light.ttf');
export const PlaywriteIN_400Regular = require('./400Regular/PlaywriteIN_400Regular.ttf');
