/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansGunjalaGondi_400Regular = require('./400Regular/NotoSansGunjalaGondi_400Regular.ttf');
export const NotoSansGunjalaGondi_500Medium = require('./500Medium/NotoSansGunjalaGondi_500Medium.ttf');
export const NotoSansGunjalaGondi_600SemiBold = require('./600SemiBold/NotoSansGunjalaGondi_600SemiBold.ttf');
export const NotoSansGunjalaGondi_700Bold = require('./700Bold/NotoSansGunjalaGondi_700Bold.ttf');
