/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywritePE_100Thin = require('./100Thin/PlaywritePE_100Thin.ttf');
export const PlaywritePE_200ExtraLight = require('./200ExtraLight/PlaywritePE_200ExtraLight.ttf');
export const PlaywritePE_300Light = require('./300Light/PlaywritePE_300Light.ttf');
export const PlaywritePE_400Regular = require('./400Regular/PlaywritePE_400Regular.ttf');
