/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Kadwa_400Regular = require('./400Regular/Kadwa_400Regular.ttf');
export const Kadwa_700Bold = require('./700Bold/Kadwa_700Bold.ttf');
