/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Mina_400Regular = require('./400Regular/Mina_400Regular.ttf');
export const Mina_700Bold = require('./700Bold/Mina_700Bold.ttf');
