/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export const __metadata__: Any;
export const Mina_400Regular: number;
export const Mina_700Bold: number;
