/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const ReemKufi_400Regular = require('./400Regular/ReemKufi_400Regular.ttf');
export const ReemKufi_500Medium = require('./500Medium/ReemKufi_500Medium.ttf');
export const ReemKufi_600SemiBold = require('./600SemiBold/ReemKufi_600SemiBold.ttf');
export const ReemKufi_700Bold = require('./700Bold/ReemKufi_700Bold.ttf');
