/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Harmattan_400Regular = require('./400Regular/Harmattan_400Regular.ttf');
export const Harmattan_500Medium = require('./500Medium/Harmattan_500Medium.ttf');
export const Harmattan_600SemiBold = require('./600SemiBold/Harmattan_600SemiBold.ttf');
export const Harmattan_700Bold = require('./700Bold/Harmattan_700Bold.ttf');
