/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Gaegu_300Light = require('./300Light/Gaegu_300Light.ttf');
export const Gaegu_400Regular = require('./400Regular/Gaegu_400Regular.ttf');
export const Gaegu_700Bold = require('./700Bold/Gaegu_700Bold.ttf');
