/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteTZ_100Thin = require('./100Thin/PlaywriteTZ_100Thin.ttf');
export const PlaywriteTZ_200ExtraLight = require('./200ExtraLight/PlaywriteTZ_200ExtraLight.ttf');
export const PlaywriteTZ_300Light = require('./300Light/PlaywriteTZ_300Light.ttf');
export const PlaywriteTZ_400Regular = require('./400Regular/PlaywriteTZ_400Regular.ttf');
