/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteBR_100Thin = require('./100Thin/PlaywriteBR_100Thin.ttf');
export const PlaywriteBR_200ExtraLight = require('./200ExtraLight/PlaywriteBR_200ExtraLight.ttf');
export const PlaywriteBR_300Light = require('./300Light/PlaywriteBR_300Light.ttf');
export const PlaywriteBR_400Regular = require('./400Regular/PlaywriteBR_400Regular.ttf');
