/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BalooDa2_400Regular = require('./400Regular/BalooDa2_400Regular.ttf');
export const BalooDa2_500Medium = require('./500Medium/BalooDa2_500Medium.ttf');
export const BalooDa2_600SemiBold = require('./600SemiBold/BalooDa2_600SemiBold.ttf');
export const BalooDa2_700Bold = require('./700Bold/BalooDa2_700Bold.ttf');
export const BalooDa2_800ExtraBold = require('./800ExtraBold/BalooDa2_800ExtraBold.ttf');
