/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const ElMessiri_400Regular = require('./400Regular/ElMessiri_400Regular.ttf');
export const ElMessiri_500Medium = require('./500Medium/ElMessiri_500Medium.ttf');
export const ElMessiri_600SemiBold = require('./600SemiBold/ElMessiri_600SemiBold.ttf');
export const ElMessiri_700Bold = require('./700Bold/ElMessiri_700Bold.ttf');
