/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const CourierPrime_400Regular = require('./400Regular/CourierPrime_400Regular.ttf');
export const CourierPrime_400Regular_Italic = require('./400Regular_Italic/CourierPrime_400Regular_Italic.ttf');
export const CourierPrime_700Bold = require('./700Bold/CourierPrime_700Bold.ttf');
export const CourierPrime_700Bold_Italic = require('./700Bold_Italic/CourierPrime_700Bold_Italic.ttf');
