/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Agdasima_400Regular = require('./400Regular/Agdasima_400Regular.ttf');
export const Agdasima_700Bold = require('./700Bold/Agdasima_700Bold.ttf');
