/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteIS_100Thin = require('./100Thin/PlaywriteIS_100Thin.ttf');
export const PlaywriteIS_200ExtraLight = require('./200ExtraLight/PlaywriteIS_200ExtraLight.ttf');
export const PlaywriteIS_300Light = require('./300Light/PlaywriteIS_300Light.ttf');
export const PlaywriteIS_400Regular = require('./400Regular/PlaywriteIS_400Regular.ttf');
