/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteAUNSW_100Thin = require('./100Thin/PlaywriteAUNSW_100Thin.ttf');
export const PlaywriteAUNSW_200ExtraLight = require('./200ExtraLight/PlaywriteAUNSW_200ExtraLight.ttf');
export const PlaywriteAUNSW_300Light = require('./300Light/PlaywriteAUNSW_300Light.ttf');
export const PlaywriteAUNSW_400Regular = require('./400Regular/PlaywriteAUNSW_400Regular.ttf');
