/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersDisplay_300Light = require('./BigShouldersDisplay_300Light.ttf');
