/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Suwannaphum_100Thin = require('./100Thin/Suwannaphum_100Thin.ttf');
export const Suwannaphum_300Light = require('./300Light/Suwannaphum_300Light.ttf');
export const Suwannaphum_400Regular = require('./400Regular/Suwannaphum_400Regular.ttf');
export const Suwannaphum_700Bold = require('./700Bold/Suwannaphum_700Bold.ttf');
export const Suwannaphum_900Black = require('./900Black/Suwannaphum_900Black.ttf');
