/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PTSansCaption_400Regular = require('./400Regular/PTSansCaption_400Regular.ttf');
export const PTSansCaption_700Bold = require('./700Bold/PTSansCaption_700Bold.ttf');
