/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const EduAUVICWANTHand_400Regular = require('./400Regular/EduAUVICWANTHand_400Regular.ttf');
export const EduAUVICWANTHand_500Medium = require('./500Medium/EduAUVICWANTHand_500Medium.ttf');
export const EduAUVICWANTHand_600SemiBold = require('./600SemiBold/EduAUVICWANTHand_600SemiBold.ttf');
export const EduAUVICWANTHand_700Bold = require('./700Bold/EduAUVICWANTHand_700Bold.ttf');
