/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const ShipporiMincho_400Regular = require('./400Regular/ShipporiMincho_400Regular.ttf');
export const ShipporiMincho_500Medium = require('./500Medium/ShipporiMincho_500Medium.ttf');
export const ShipporiMincho_600SemiBold = require('./600SemiBold/ShipporiMincho_600SemiBold.ttf');
export const ShipporiMincho_700Bold = require('./700Bold/ShipporiMincho_700Bold.ttf');
export const ShipporiMincho_800ExtraBold = require('./800ExtraBold/ShipporiMincho_800ExtraBold.ttf');
