/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Corinthia_400Regular = require('./400Regular/Corinthia_400Regular.ttf');
export const Corinthia_700Bold = require('./700Bold/Corinthia_700Bold.ttf');
