/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const QwitcherGrypen_400Regular = require('./400Regular/QwitcherGrypen_400Regular.ttf');
export const QwitcherGrypen_700Bold = require('./700Bold/QwitcherGrypen_700Bold.ttf');
