/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersStencilDisplay_900Black = require('./BigShouldersStencilDisplay_900Black.ttf');
