/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const CormorantUpright_300Light = require('./300Light/CormorantUpright_300Light.ttf');
export const CormorantUpright_400Regular = require('./400Regular/CormorantUpright_400Regular.ttf');
export const CormorantUpright_500Medium = require('./500Medium/CormorantUpright_500Medium.ttf');
export const CormorantUpright_600SemiBold = require('./600SemiBold/CormorantUpright_600SemiBold.ttf');
export const CormorantUpright_700Bold = require('./700Bold/CormorantUpright_700Bold.ttf');
