/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Sintony_400Regular = require('./400Regular/Sintony_400Regular.ttf');
export const Sintony_700Bold = require('./700Bold/Sintony_700Bold.ttf');
