/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteDEVA_100Thin = require('./100Thin/PlaywriteDEVA_100Thin.ttf');
export const PlaywriteDEVA_200ExtraLight = require('./200ExtraLight/PlaywriteDEVA_200ExtraLight.ttf');
export const PlaywriteDEVA_300Light = require('./300Light/PlaywriteDEVA_300Light.ttf');
export const PlaywriteDEVA_400Regular = require('./400Regular/PlaywriteDEVA_400Regular.ttf');
