/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Comfortaa_300Light = require('./300Light/Comfortaa_300Light.ttf');
export const Comfortaa_400Regular = require('./400Regular/Comfortaa_400Regular.ttf');
export const Comfortaa_500Medium = require('./500Medium/Comfortaa_500Medium.ttf');
export const Comfortaa_600SemiBold = require('./600SemiBold/Comfortaa_600SemiBold.ttf');
export const Comfortaa_700Bold = require('./700Bold/Comfortaa_700Bold.ttf');
