/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansLao_100Thin = require('./100Thin/NotoSansLao_100Thin.ttf');
export const NotoSansLao_200ExtraLight = require('./200ExtraLight/NotoSansLao_200ExtraLight.ttf');
export const NotoSansLao_300Light = require('./300Light/NotoSansLao_300Light.ttf');
export const NotoSansLao_400Regular = require('./400Regular/NotoSansLao_400Regular.ttf');
export const NotoSansLao_500Medium = require('./500Medium/NotoSansLao_500Medium.ttf');
export const NotoSansLao_600SemiBold = require('./600SemiBold/NotoSansLao_600SemiBold.ttf');
export const NotoSansLao_700Bold = require('./700Bold/NotoSansLao_700Bold.ttf');
export const NotoSansLao_800ExtraBold = require('./800ExtraBold/NotoSansLao_800ExtraBold.ttf');
export const NotoSansLao_900Black = require('./900Black/NotoSansLao_900Black.ttf');
