/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersDisplay_800ExtraBold = require('./BigShouldersDisplay_800ExtraBold.ttf');
