/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Anaheim_400Regular = require('./400Regular/Anaheim_400Regular.ttf');
export const Anaheim_500Medium = require('./500Medium/Anaheim_500Medium.ttf');
export const Anaheim_600SemiBold = require('./600SemiBold/Anaheim_600SemiBold.ttf');
export const Anaheim_700Bold = require('./700Bold/Anaheim_700Bold.ttf');
export const Anaheim_800ExtraBold = require('./800ExtraBold/Anaheim_800ExtraBold.ttf');
