/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansGeorgian_100Thin = require('./100Thin/NotoSansGeorgian_100Thin.ttf');
export const NotoSansGeorgian_200ExtraLight = require('./200ExtraLight/NotoSansGeorgian_200ExtraLight.ttf');
export const NotoSansGeorgian_300Light = require('./300Light/NotoSansGeorgian_300Light.ttf');
export const NotoSansGeorgian_400Regular = require('./400Regular/NotoSansGeorgian_400Regular.ttf');
export const NotoSansGeorgian_500Medium = require('./500Medium/NotoSansGeorgian_500Medium.ttf');
export const NotoSansGeorgian_600SemiBold = require('./600SemiBold/NotoSansGeorgian_600SemiBold.ttf');
export const NotoSansGeorgian_700Bold = require('./700Bold/NotoSansGeorgian_700Bold.ttf');
export const NotoSansGeorgian_800ExtraBold = require('./800ExtraBold/NotoSansGeorgian_800ExtraBold.ttf');
export const NotoSansGeorgian_900Black = require('./900Black/NotoSansGeorgian_900Black.ttf');
