/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Solitreo_400Regular = require('./400Regular/Solitreo_400Regular.ttf');
