/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteCL_100Thin = require('./100Thin/PlaywriteCL_100Thin.ttf');
export const PlaywriteCL_200ExtraLight = require('./200ExtraLight/PlaywriteCL_200ExtraLight.ttf');
export const PlaywriteCL_300Light = require('./300Light/PlaywriteCL_300Light.ttf');
export const PlaywriteCL_400Regular = require('./400Regular/PlaywriteCL_400Regular.ttf');
