/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const LobsterTwo_400Regular = require('./400Regular/LobsterTwo_400Regular.ttf');
export const LobsterTwo_400Regular_Italic = require('./400Regular_Italic/LobsterTwo_400Regular_Italic.ttf');
export const LobsterTwo_700Bold = require('./700Bold/LobsterTwo_700Bold.ttf');
export const LobsterTwo_700Bold_Italic = require('./700Bold_Italic/LobsterTwo_700Bold_Italic.ttf');
