/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansDuployan_400Regular = require('./400Regular/NotoSansDuployan_400Regular.ttf');
export const NotoSansDuployan_700Bold = require('./700Bold/NotoSansDuployan_700Bold.ttf');
