/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Cousine_400Regular = require('./400Regular/Cousine_400Regular.ttf');
export const Cousine_400Regular_Italic = require('./400Regular_Italic/Cousine_400Regular_Italic.ttf');
export const Cousine_700Bold = require('./700Bold/Cousine_700Bold.ttf');
export const Cousine_700Bold_Italic = require('./700Bold_Italic/Cousine_700Bold_Italic.ttf');
