/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const AnonymousPro_400Regular = require('./400Regular/AnonymousPro_400Regular.ttf');
export const AnonymousPro_400Regular_Italic = require('./400Regular_Italic/AnonymousPro_400Regular_Italic.ttf');
export const AnonymousPro_700Bold = require('./700Bold/AnonymousPro_700Bold.ttf');
export const AnonymousPro_700Bold_Italic = require('./700Bold_Italic/AnonymousPro_700Bold_Italic.ttf');
