/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersStencilText_200ExtraLight = require('./BigShouldersStencilText_200ExtraLight.ttf');
