/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Alef_400Regular = require('./400Regular/Alef_400Regular.ttf');
export const Alef_700Bold = require('./700Bold/Alef_700Bold.ttf');
