/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansSymbols_100Thin = require('./100Thin/NotoSansSymbols_100Thin.ttf');
export const NotoSansSymbols_200ExtraLight = require('./200ExtraLight/NotoSansSymbols_200ExtraLight.ttf');
export const NotoSansSymbols_300Light = require('./300Light/NotoSansSymbols_300Light.ttf');
export const NotoSansSymbols_400Regular = require('./400Regular/NotoSansSymbols_400Regular.ttf');
export const NotoSansSymbols_500Medium = require('./500Medium/NotoSansSymbols_500Medium.ttf');
export const NotoSansSymbols_600SemiBold = require('./600SemiBold/NotoSansSymbols_600SemiBold.ttf');
export const NotoSansSymbols_700Bold = require('./700Bold/NotoSansSymbols_700Bold.ttf');
export const NotoSansSymbols_800ExtraBold = require('./800ExtraBold/NotoSansSymbols_800ExtraBold.ttf');
export const NotoSansSymbols_900Black = require('./900Black/NotoSansSymbols_900Black.ttf');
