/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Coustard_400Regular = require('./400Regular/Coustard_400Regular.ttf');
export const Coustard_900Black = require('./900Black/Coustard_900Black.ttf');
