/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const YanoneKaffeesatz_200ExtraLight = require('./200ExtraLight/YanoneKaffeesatz_200ExtraLight.ttf');
export const YanoneKaffeesatz_300Light = require('./300Light/YanoneKaffeesatz_300Light.ttf');
export const YanoneKaffeesatz_400Regular = require('./400Regular/YanoneKaffeesatz_400Regular.ttf');
export const YanoneKaffeesatz_500Medium = require('./500Medium/YanoneKaffeesatz_500Medium.ttf');
export const YanoneKaffeesatz_600SemiBold = require('./600SemiBold/YanoneKaffeesatz_600SemiBold.ttf');
export const YanoneKaffeesatz_700Bold = require('./700Bold/YanoneKaffeesatz_700Bold.ttf');
