/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BIZUDPMincho_400Regular = require('./400Regular/BIZUDPMincho_400Regular.ttf');
export const BIZUDPMincho_700Bold = require('./700Bold/BIZUDPMincho_700Bold.ttf');
