/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSerifToto_400Regular = require('./400Regular/NotoSerifToto_400Regular.ttf');
export const NotoSerifToto_500Medium = require('./500Medium/NotoSerifToto_500Medium.ttf');
export const NotoSerifToto_600SemiBold = require('./600SemiBold/NotoSerifToto_600SemiBold.ttf');
export const NotoSerifToto_700Bold = require('./700Bold/NotoSerifToto_700Bold.ttf');
