/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteZA_100Thin = require('./100Thin/PlaywriteZA_100Thin.ttf');
export const PlaywriteZA_200ExtraLight = require('./200ExtraLight/PlaywriteZA_200ExtraLight.ttf');
export const PlaywriteZA_300Light = require('./300Light/PlaywriteZA_300Light.ttf');
export const PlaywriteZA_400Regular = require('./400Regular/PlaywriteZA_400Regular.ttf');
