/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Oswald_200ExtraLight = require('./200ExtraLight/Oswald_200ExtraLight.ttf');
export const Oswald_300Light = require('./300Light/Oswald_300Light.ttf');
export const Oswald_400Regular = require('./400Regular/Oswald_400Regular.ttf');
export const Oswald_500Medium = require('./500Medium/Oswald_500Medium.ttf');
export const Oswald_600SemiBold = require('./600SemiBold/Oswald_600SemiBold.ttf');
export const Oswald_700Bold = require('./700Bold/Oswald_700Bold.ttf');
