/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Sarala_400Regular = require('./400Regular/Sarala_400Regular.ttf');
export const Sarala_700Bold = require('./700Bold/Sarala_700Bold.ttf');
