/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const MarkaziText_400Regular = require('./400Regular/MarkaziText_400Regular.ttf');
export const MarkaziText_500Medium = require('./500Medium/MarkaziText_500Medium.ttf');
export const MarkaziText_600SemiBold = require('./600SemiBold/MarkaziText_600SemiBold.ttf');
export const MarkaziText_700Bold = require('./700Bold/MarkaziText_700Bold.ttf');
