/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BonaNova_400Regular = require('./400Regular/BonaNova_400Regular.ttf');
export const BonaNova_400Regular_Italic = require('./400Regular_Italic/BonaNova_400Regular_Italic.ttf');
export const BonaNova_700Bold = require('./700Bold/BonaNova_700Bold.ttf');
