/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Trochut_400Regular = require('./400Regular/Trochut_400Regular.ttf');
export const Trochut_400Regular_Italic = require('./400Regular_Italic/Trochut_400Regular_Italic.ttf');
export const Trochut_700Bold = require('./700Bold/Trochut_700Bold.ttf');
