/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const HindGuntur_300Light = require('./300Light/HindGuntur_300Light.ttf');
export const HindGuntur_400Regular = require('./400Regular/HindGuntur_400Regular.ttf');
export const HindGuntur_500Medium = require('./500Medium/HindGuntur_500Medium.ttf');
export const HindGuntur_600SemiBold = require('./600SemiBold/HindGuntur_600SemiBold.ttf');
export const HindGuntur_700Bold = require('./700Bold/HindGuntur_700Bold.ttf');
