/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteCA_100Thin = require('./100Thin/PlaywriteCA_100Thin.ttf');
export const PlaywriteCA_200ExtraLight = require('./200ExtraLight/PlaywriteCA_200ExtraLight.ttf');
export const PlaywriteCA_300Light = require('./300Light/PlaywriteCA_300Light.ttf');
export const PlaywriteCA_400Regular = require('./400Regular/PlaywriteCA_400Regular.ttf');
