/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const QuattrocentoSans_400Regular = require('./400Regular/QuattrocentoSans_400Regular.ttf');
export const QuattrocentoSans_400Regular_Italic = require('./400Regular_Italic/QuattrocentoSans_400Regular_Italic.ttf');
export const QuattrocentoSans_700Bold = require('./700Bold/QuattrocentoSans_700Bold.ttf');
export const QuattrocentoSans_700Bold_Italic = require('./700Bold_Italic/QuattrocentoSans_700Bold_Italic.ttf');
