/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const LilitaOne_400Regular = require('./400Regular/LilitaOne_400Regular.ttf');
