/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const AlumniSansInlineOne_400Regular = require('./400Regular/AlumniSansInlineOne_400Regular.ttf');
export const AlumniSansInlineOne_400Regular_Italic = require('./400Regular_Italic/AlumniSansInlineOne_400Regular_Italic.ttf');
