/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Fredoka_300Light = require('./300Light/Fredoka_300Light.ttf');
export const Fredoka_400Regular = require('./400Regular/Fredoka_400Regular.ttf');
export const Fredoka_500Medium = require('./500Medium/Fredoka_500Medium.ttf');
export const Fredoka_600SemiBold = require('./600SemiBold/Fredoka_600SemiBold.ttf');
export const Fredoka_700Bold = require('./700Bold/Fredoka_700Bold.ttf');
