/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSansBalinese_400Regular = require('./400Regular/NotoSansBalinese_400Regular.ttf');
export const NotoSansBalinese_500Medium = require('./500Medium/NotoSansBalinese_500Medium.ttf');
export const NotoSansBalinese_600SemiBold = require('./600SemiBold/NotoSansBalinese_600SemiBold.ttf');
export const NotoSansBalinese_700Bold = require('./700Bold/NotoSansBalinese_700Bold.ttf');
