/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Ruda_400Regular = require('./400Regular/Ruda_400Regular.ttf');
export const Ruda_500Medium = require('./500Medium/Ruda_500Medium.ttf');
export const Ruda_600SemiBold = require('./600SemiBold/Ruda_600SemiBold.ttf');
export const Ruda_700Bold = require('./700Bold/Ruda_700Bold.ttf');
export const Ruda_800ExtraBold = require('./800ExtraBold/Ruda_800ExtraBold.ttf');
export const Ruda_900Black = require('./900Black/Ruda_900Black.ttf');
