/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const VesperLibre_400Regular = require('./400Regular/VesperLibre_400Regular.ttf');
export const VesperLibre_500Medium = require('./500Medium/VesperLibre_500Medium.ttf');
export const VesperLibre_700Bold = require('./700Bold/VesperLibre_700Bold.ttf');
export const VesperLibre_900Black = require('./900Black/VesperLibre_900Black.ttf');
