/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Karma_300Light = require('./300Light/Karma_300Light.ttf');
export const Karma_400Regular = require('./400Regular/Karma_400Regular.ttf');
export const Karma_500Medium = require('./500Medium/Karma_500Medium.ttf');
export const Karma_600SemiBold = require('./600SemiBold/Karma_600SemiBold.ttf');
export const Karma_700Bold = require('./700Bold/Karma_700Bold.ttf');
