/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const GowunBatang_400Regular = require('./400Regular/GowunBatang_400Regular.ttf');
export const GowunBatang_700Bold = require('./700Bold/GowunBatang_700Bold.ttf');
