/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PragatiNarrow_400Regular = require('./400Regular/PragatiNarrow_400Regular.ttf');
export const PragatiNarrow_700Bold = require('./700Bold/PragatiNarrow_700Bold.ttf');
