/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteFRModerne_100Thin = require('./100Thin/PlaywriteFRModerne_100Thin.ttf');
export const PlaywriteFRModerne_200ExtraLight = require('./200ExtraLight/PlaywriteFRModerne_200ExtraLight.ttf');
export const PlaywriteFRModerne_300Light = require('./300Light/PlaywriteFRModerne_300Light.ttf');
export const PlaywriteFRModerne_400Regular = require('./400Regular/PlaywriteFRModerne_400Regular.ttf');
