/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Jaldi_400Regular = require('./400Regular/Jaldi_400Regular.ttf');
export const Jaldi_700Bold = require('./700Bold/Jaldi_700Bold.ttf');
