/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const FiraMono_400Regular = require('./400Regular/FiraMono_400Regular.ttf');
export const FiraMono_500Medium = require('./500Medium/FiraMono_500Medium.ttf');
export const FiraMono_700Bold = require('./700Bold/FiraMono_700Bold.ttf');
