/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Unkempt_400Regular = require('./400Regular/Unkempt_400Regular.ttf');
export const Unkempt_700Bold = require('./700Bold/Unkempt_700Bold.ttf');
