/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Padauk_400Regular = require('./400Regular/Padauk_400Regular.ttf');
export const Padauk_700Bold = require('./700Bold/Padauk_700Bold.ttf');
