/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const MiriamLibre_400Regular = require('./400Regular/MiriamLibre_400Regular.ttf');
export const MiriamLibre_500Medium = require('./500Medium/MiriamLibre_500Medium.ttf');
export const MiriamLibre_600SemiBold = require('./600SemiBold/MiriamLibre_600SemiBold.ttf');
export const MiriamLibre_700Bold = require('./700Bold/MiriamLibre_700Bold.ttf');
