/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteAR_100Thin = require('./100Thin/PlaywriteAR_100Thin.ttf');
export const PlaywriteAR_200ExtraLight = require('./200ExtraLight/PlaywriteAR_200ExtraLight.ttf');
export const PlaywriteAR_300Light = require('./300Light/PlaywriteAR_300Light.ttf');
export const PlaywriteAR_400Regular = require('./400Regular/PlaywriteAR_400Regular.ttf');
