/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const TurretRoad_200ExtraLight = require('./200ExtraLight/TurretRoad_200ExtraLight.ttf');
export const TurretRoad_300Light = require('./300Light/TurretRoad_300Light.ttf');
export const TurretRoad_400Regular = require('./400Regular/TurretRoad_400Regular.ttf');
export const TurretRoad_500Medium = require('./500Medium/TurretRoad_500Medium.ttf');
export const TurretRoad_700Bold = require('./700Bold/TurretRoad_700Bold.ttf');
export const TurretRoad_800ExtraBold = require('./800ExtraBold/TurretRoad_800ExtraBold.ttf');
