/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Tinos_400Regular = require('./400Regular/Tinos_400Regular.ttf');
export const Tinos_400Regular_Italic = require('./400Regular_Italic/Tinos_400Regular_Italic.ttf');
export const Tinos_700Bold = require('./700Bold/Tinos_700Bold.ttf');
export const Tinos_700Bold_Italic = require('./700Bold_Italic/Tinos_700Bold_Italic.ttf');
