/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoSerifYezidi_400Regular = require('./400Regular/NotoSerifYezidi_400Regular.ttf');
export const NotoSerifYezidi_500Medium = require('./500Medium/NotoSerifYezidi_500Medium.ttf');
export const NotoSerifYezidi_600SemiBold = require('./600SemiBold/NotoSerifYezidi_600SemiBold.ttf');
export const NotoSerifYezidi_700Bold = require('./700Bold/NotoSerifYezidi_700Bold.ttf');
