/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersStencilDisplay_700Bold = require('./BigShouldersStencilDisplay_700Bold.ttf');
