/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Laila_300Light = require('./300Light/Laila_300Light.ttf');
export const Laila_400Regular = require('./400Regular/Laila_400Regular.ttf');
export const Laila_500Medium = require('./500Medium/Laila_500Medium.ttf');
export const Laila_600SemiBold = require('./600SemiBold/Laila_600SemiBold.ttf');
export const Laila_700Bold = require('./700Bold/Laila_700Bold.ttf');
