/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BIZUDGothic_400Regular = require('./400Regular/BIZUDGothic_400Regular.ttf');
export const BIZUDGothic_700Bold = require('./700Bold/BIZUDGothic_700Bold.ttf');
