/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Ranga_400Regular = require('./400Regular/Ranga_400Regular.ttf');
export const Ranga_700Bold = require('./700Bold/Ranga_700Bold.ttf');
