/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Caveat_400Regular = require('./400Regular/Caveat_400Regular.ttf');
export const Caveat_500Medium = require('./500Medium/Caveat_500Medium.ttf');
export const Caveat_600SemiBold = require('./600SemiBold/Caveat_600SemiBold.ttf');
export const Caveat_700Bold = require('./700Bold/Caveat_700Bold.ttf');
