/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Codystar_300Light = require('./300Light/Codystar_300Light.ttf');
export const Codystar_400Regular = require('./400Regular/Codystar_400Regular.ttf');
