/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Pridi_200ExtraLight = require('./200ExtraLight/Pridi_200ExtraLight.ttf');
export const Pridi_300Light = require('./300Light/Pridi_300Light.ttf');
export const Pridi_400Regular = require('./400Regular/Pridi_400Regular.ttf');
export const Pridi_500Medium = require('./500Medium/Pridi_500Medium.ttf');
export const Pridi_600SemiBold = require('./600SemiBold/Pridi_600SemiBold.ttf');
export const Pridi_700Bold = require('./700Bold/Pridi_700Bold.ttf');
