/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const DavidLibre_400Regular = require('./400Regular/DavidLibre_400Regular.ttf');
export const DavidLibre_500Medium = require('./500Medium/DavidLibre_500Medium.ttf');
export const DavidLibre_700Bold = require('./700Bold/DavidLibre_700Bold.ttf');
