/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Monda_400Regular = require('./400Regular/Monda_400Regular.ttf');
export const Monda_500Medium = require('./500Medium/Monda_500Medium.ttf');
export const Monda_600SemiBold = require('./600SemiBold/Monda_600SemiBold.ttf');
export const Monda_700Bold = require('./700Bold/Monda_700Bold.ttf');
