/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Cardo_400Regular = require('./400Regular/Cardo_400Regular.ttf');
export const Cardo_400Regular_Italic = require('./400Regular_Italic/Cardo_400Regular_Italic.ttf');
export const Cardo_700Bold = require('./700Bold/Cardo_700Bold.ttf');
