/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BalsamiqSans_400Regular = require('./400Regular/BalsamiqSans_400Regular.ttf');
export const BalsamiqSans_400Regular_Italic = require('./400Regular_Italic/BalsamiqSans_400Regular_Italic.ttf');
export const BalsamiqSans_700Bold = require('./700Bold/BalsamiqSans_700Bold.ttf');
export const BalsamiqSans_700Bold_Italic = require('./700Bold_Italic/BalsamiqSans_700Bold_Italic.ttf');
