/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const VollkornSC_400Regular = require('./400Regular/VollkornSC_400Regular.ttf');
export const VollkornSC_600SemiBold = require('./600SemiBold/VollkornSC_600SemiBold.ttf');
export const VollkornSC_700Bold = require('./700Bold/VollkornSC_700Bold.ttf');
export const VollkornSC_900Black = require('./900Black/VollkornSC_900Black.ttf');
