/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const PlaywriteCU_100Thin = require('./100Thin/PlaywriteCU_100Thin.ttf');
export const PlaywriteCU_200ExtraLight = require('./200ExtraLight/PlaywriteCU_200ExtraLight.ttf');
export const PlaywriteCU_300Light = require('./300Light/PlaywriteCU_300Light.ttf');
export const PlaywriteCU_400Regular = require('./400Regular/PlaywriteCU_400Regular.ttf');
