/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Dongle_300Light = require('./300Light/Dongle_300Light.ttf');
export const Dongle_400Regular = require('./400Regular/Dongle_400Regular.ttf');
export const Dongle_700Bold = require('./700Bold/Dongle_700Bold.ttf');
