/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Ruwudu_400Regular = require('./400Regular/Ruwudu_400Regular.ttf');
export const Ruwudu_500Medium = require('./500Medium/Ruwudu_500Medium.ttf');
export const Ruwudu_600SemiBold = require('./600SemiBold/Ruwudu_600SemiBold.ttf');
export const Ruwudu_700Bold = require('./700Bold/Ruwudu_700Bold.ttf');
