/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const ComicNeue_300Light = require('./300Light/ComicNeue_300Light.ttf');
export const ComicNeue_300Light_Italic = require('./300Light_Italic/ComicNeue_300Light_Italic.ttf');
export const ComicNeue_400Regular = require('./400Regular/ComicNeue_400Regular.ttf');
export const ComicNeue_400Regular_Italic = require('./400Regular_Italic/ComicNeue_400Regular_Italic.ttf');
export const ComicNeue_700Bold = require('./700Bold/ComicNeue_700Bold.ttf');
export const ComicNeue_700Bold_Italic = require('./700Bold_Italic/ComicNeue_700Bold_Italic.ttf');
