/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Gupter_400Regular = require('./400Regular/Gupter_400Regular.ttf');
export const Gupter_500Medium = require('./500Medium/Gupter_500Medium.ttf');
export const Gupter_700Bold = require('./700Bold/Gupter_700Bold.ttf');
