/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const NotoNaskhArabic_400Regular = require('./400Regular/NotoNaskhArabic_400Regular.ttf');
export const NotoNaskhArabic_500Medium = require('./500Medium/NotoNaskhArabic_500Medium.ttf');
export const NotoNaskhArabic_600SemiBold = require('./600SemiBold/NotoNaskhArabic_600SemiBold.ttf');
export const NotoNaskhArabic_700Bold = require('./700Bold/NotoNaskhArabic_700Bold.ttf');
