/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export const BigShouldersStencilText_100Thin = require('./BigShouldersStencilText_100Thin.ttf');
