/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const KaiseiTokumin_400Regular = require('./400Regular/KaiseiTokumin_400Regular.ttf');
export const KaiseiTokumin_500Medium = require('./500Medium/KaiseiTokumin_500Medium.ttf');
export const KaiseiTokumin_700Bold = require('./700Bold/KaiseiTokumin_700Bold.ttf');
export const KaiseiTokumin_800ExtraBold = require('./800ExtraBold/KaiseiTokumin_800ExtraBold.ttf');
