/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const Sniglet_400Regular = require('./400Regular/Sniglet_400Regular.ttf');
export const Sniglet_800ExtraBold = require('./800ExtraBold/Sniglet_800ExtraBold.ttf');
