/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const BIZUDPGothic_400Regular = require('./400Regular/BIZUDPGothic_400Regular.ttf');
export const BIZUDPGothic_700Bold = require('./700Bold/BIZUDPGothic_700Bold.ttf');
