/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const EduAUVICWANTGuides_400Regular = require('./400Regular/EduAUVICWANTGuides_400Regular.ttf');
export const EduAUVICWANTGuides_500Medium = require('./500Medium/EduAUVICWANTGuides_500Medium.ttf');
export const EduAUVICWANTGuides_600SemiBold = require('./600SemiBold/EduAUVICWANTGuides_600SemiBold.ttf');
export const EduAUVICWANTGuides_700Bold = require('./700Bold/EduAUVICWANTGuides_700Bold.ttf');
