/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///

export * from './useFonts/';

export { default as __metadata__ } from './metadata.json';
export const AnekOdia_100Thin = require('./100Thin/AnekOdia_100Thin.ttf');
export const AnekOdia_200ExtraLight = require('./200ExtraLight/AnekOdia_200ExtraLight.ttf');
export const AnekOdia_300Light = require('./300Light/AnekOdia_300Light.ttf');
export const AnekOdia_400Regular = require('./400Regular/AnekOdia_400Regular.ttf');
export const AnekOdia_500Medium = require('./500Medium/AnekOdia_500Medium.ttf');
export const AnekOdia_600SemiBold = require('./600SemiBold/AnekOdia_600SemiBold.ttf');
export const AnekOdia_700Bold = require('./700Bold/AnekOdia_700Bold.ttf');
export const AnekOdia_800ExtraBold = require('./800ExtraBold/AnekOdia_800ExtraBold.ttf');
